# Generated by Django 3.0.3 on 2020-02-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
